### Get a count on the number of records
GET http://localhost:8080/restapi/EnforcementZoneCentres/count

### Get an entity with siteId of 4062
GET http://localhost:8080/restapi/EnforcementZoneCentres/4062
