### Get all TodoItems
GET http://localhost:8181/restapi/TodoItems

### Get a single TodoItem with an id of 1
GET http://localhost:8181/restapi/TodoItems/1

### POST a new TodoItem with valid data
POST http://localhost:8181/restapi/TodoItems
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Demo Sales creating a TodoItem",
  "complete": false
}

### POST a new TodoItem with account that does not have permission
POST http://localhost:8181/restapi/TodoItems
Content-Type: application/json
Authorization: Bearer {{jwtTokenJchen}}

{
  "name": "Demo Finance creating a TodoItem",
  "complete": true
}

### Post a new TodoItem with invalid data
POST http://localhost:8181/restapi/TodoItems
Content-Type: application/json

{
  "name": "     ",
  "complete": false
}

### Get a single TodoItem with an id of 4
GET http://localhost:8181/restapi/TodoItems/4

### Update TodoItem with an id of 4 with valid data
PUT http://localhost:8181/restapi/TodoItems/4
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "id": 4,
  "name": "Update RBAC example",
  "complete": true,
  "version": 0
}


### Update TodoItem with role that does to have permission
PUT http://localhost:8181/restapi/TodoItems/4
Content-Type: application/json
Authorization: Bearer {{jwtTokenJchen}}

{
  "id": 4,
  "name": "Update RBAC example should fail",
  "complete": true,
  "version": 1
}

### Delete an TodoItem with an id of 2
DELETE http://localhost:8181/restapi/TodoItems/2
Authorization: Bearer {{jwtToken}}

### Delete an TodoItem with an id of 4
DELETE http://localhost:8181/restapi/TodoItems/4
Authorization: Bearer {{jwtTokenJchen}}