build:
  bootableJar:
    builderImage: 'registry.access.redhat.com/ubi8/openjdk-17:latest'
  contextDir: dmit2015-openshift-jaxrs-demo
  mode: bootable-jar
  ref: main
  uri: your-gith-repo.git
deploy:
  env:
    - name: JAVA_DEBUG
      value: 'true'
    - name: JAVA_DEBUG_PORT
      value: '8787'
  replicas: 1
