### Get all TodoItemsDto
GET http://localhost:8182/restapi/TodoItemsDto
Authorization: Bearer {{jwtToken}}

### Get a single TodoItem with an id of 1
GET http://localhost:8182/restapi/TodoItemsDto/1
Authorization: Bearer {{jwtToken}}

### POST a new TodoItem with valid data
POST http://localhost:8182/restapi/TodoItemsDto
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Start DMIT2015 Assignment 3",
  "complete": false
}

### Post a new TodoItem with invalid data
POST http://localhost:8182/restapi/TodoItemsDto
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "     ",
  "complete": false
}

### Get a single TodoItem with an id of 4
GET http://localhost:8182/restapi/TodoItemsDto/4
Authorization: Bearer {{jwtToken}}

### Update TodoItem with an id of 4 with valid data
PUT http://localhost:8182/restapi/TodoItemsDto/4
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "id": 4,
  "name": "Commit DMIT2015 Assignment 6",
  "complete": true,
  "version": 1
}

### Delete an TodoItem with an id of 2
DELETE http://localhost:8182/restapi/TodoItemsDto/2
Authorization: Bearer {{jwtToken}}

### Delete an TodoItem with an id of 4
DELETE http://localhost:8182/restapi/TodoItemsDto/4
Authorization: Bearer {{jwtToken}}